// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8NeKO7PedY-uofO-Nr5nzNpR1PIcmeys',
    appId: '1:366435590256:web:4516cf2ea8f08a55e794b5',
    messagingSenderId: '366435590256',
    projectId: 'uavcontrollerapp',
    authDomain: 'uavcontrollerapp.firebaseapp.com',
    databaseURL: 'https://uavcontrollerapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uavcontrollerapp.firebasestorage.app',
    measurementId: 'G-6MH71SZQVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaUgffqPhHpOt_jA0yR1mY7iG1YHydXTM',
    appId: '1:366435590256:android:1bded198cd04c45ce794b5',
    messagingSenderId: '366435590256',
    projectId: 'uavcontrollerapp',
    databaseURL: 'https://uavcontrollerapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uavcontrollerapp.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8NeKO7PedY-uofO-Nr5nzNpR1PIcmeys',
    appId: '1:366435590256:web:c49166b3d5df43a9e794b5',
    messagingSenderId: '366435590256',
    projectId: 'uavcontrollerapp',
    authDomain: 'uavcontrollerapp.firebaseapp.com',
    databaseURL: 'https://uavcontrollerapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uavcontrollerapp.firebasestorage.app',
    measurementId: 'G-XHK90BR8H4',
  );
}
